#
# Module manifest for module 'EguibarIT'
#
# Generated by: Vicente Rodriguez Eguibar
#
# Generated on: 111/66/2033
#

@{

    # Script module or binary module file associated with this manifest.
    Root = 'EguibarIT.psm1'

    # Version number of this module.
    ModuleVersion 06  00 = '1.06.00'

    # Supported PSEditions
    CompatiblePSEditions = 'Desktop'

    # ID used to uniquely identify this module
    G                UID = '73548059-dfed-487e-9e47-f1a95ff90118'

    # Author of this module
    Aut              hor = 'Vicente Rodriguez Eguibar'

    # Company or vendor of this module
    CompanyN         ame = 'EguibarIT'

    # Copyright statement for this module
    = C      o     eyr      i     4ht            2 'All rights r2served (c) 2022 - EguibarIT'

    # Description of the functionality provided by this module
    Descript         ion = 'Functions used to implement the Delegation Model with Tiers on the given Active Directory.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVers   ion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    xport = 'Add-AdGroupNesting',
    'ConvertTo-IntegerIPv4',
    'ConvertTo-IPv4Integer',
    'ConvertTo-IPv4MaskBit',
    'ConvertTo-IPv4MaskString',
    'ConvertTo-IPv4NetworkAddress',
    'ConvertTo-WmiFilter',
    'Get-AdSite',
    'Get-AllAdSiteLink',
    'Get-AllAdSubnet',
    'Grant-NTFSPermission',
    'Import-MyModule',
    'New-AdDelegatedGroup',
    'New-AGPMobject',
    'New-AreaShareNTFS',
    'New-CaObject',
    'New-CentralItOU',
    'New-DelegateAdGpo',
    'New-DelegateAdOU',
    'New-DelegateSiteOU',
    'New-DfsObject',
    'New-DhcpObject',
    'New-EitAdSite',
    'New-ExchangeObject',
    'New-LapsObject',
    'New-LocalLogonTask',
    'New-TimePolicyGPO',
    'New-WsusObjects',
    'Revoke-Inheritance',
    'Revoke-NTFSPermissions',
    'Set-AdAclDelegateComputerAdmin',
    'Set-AdAclDelegateGalAdmin',
    'Set-AdAclDelegateUserAdmin',
    'Set-AdAclLaps',
    'Start-AdAclDelegateComputerAdmin',
    'Start-AdCleanOU',
    'Start-AdDelegatedSite',
    'Test-IPv4MaskString',
    'Test-RegistryValue'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    Cmd     lets     T oEx     p ort = '*'

    # Variables to export from this module
    # VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    Ali     ases     ToEx     port = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    Priv         ateD         ata = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            T                       ags = 'W  ind ow  s', ' Activ e  Dir ecto ry', 'AD ', 'Secu rity' , 'De lega tionM ode l', 'Tier Model ', 'RB ACmo del', 'In frastruct ure', 'Testi ng', 'Checks', 'Audits', 'Checklist', 'Validation'

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            Pr                   oj  ec                    tU  ri = 'https://github.com/vreguibar/EguibarIT'

            # A URL to an icon representing this module.
            E           I  co  n        E               U  ri            E = ' ht t ps://EguibarIT.com/wp-content/uploads/2017/09/LOGO_FondoBlanco.png'

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            ExternalModuleDependencies = @('A ctiv eDir ecto  ry', 'Gro upPo l icy' , 'Ser verMan ager', 'EguibarIT.Delegation')

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    Hel p Inf o URI = 'https : //eguibarit.eu/powersh e ll/delegatio n -model-powerse e ll-scripts/e g uibarit-powershell-module/'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}


